version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: simplelms_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - ./code:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
